bldr:
    name: LMammino/Efoundation
    profiles:
        default:
            description: default build task
            tasks:
                - lintPhp
                - phpcs
                - testPhpUnit
                - cleanDoc
                - buildDoc

        doc:
            description: Generates API doc
            tasks:
                - cleanDoc
                - buildDoc
        test:
            description: Run the test suite
            tasks:
                - lintPhp
                - testPhpUnit

    tasks:
        cleanDoc:
            description: Clean up files
            calls:
                -
                    type: filesystem:remove
                    task: filesystem:remove
                    files: ['doc/build', 'doc/cache']
        buildDoc:
            description: Build the documentation
            calls:
                -
                    type: exec
                    executable: vendor/bin/sami.php 
                    arguments: ["update", "doc/config.php"]
        testPhpUnit:
            description: PhpUnit tests
            calls:
                -
                    type: exec
                    failOnError: true
                    executable: vendor/bin/phpunit
                    arguments: ["-c", "phpunit.xml.dist"]
        lintPhp:
            description: Lints the files of the project
            calls:
                -
                    type: apply
                    failOnError: true
                    src:
                        - { path: [src, tests], files: *.php, recursive: true }
                    executable: php
                    arguments: [-l]
        phpcs:
            description: Runs the PHP Code Sniffer
            calls:
                -
                    type: exec
                    executable: vendor/bin/phpcs
                    arguments: ["--standard=PSR2", "src/"]